-- Group scopes are worker jobs, never synthetic pool IDs. Counts use the same
-- stored eligible-row predicate as pool jobs, summed across visible members.
BEGIN;

CREATE FUNCTION public.statistics_group_keys() RETURNS SETOF text
LANGUAGE sql IMMUTABLE SET search_path=public AS $$
  VALUES ('group:limited'), ('group:weapon_limited'), ('group:weapon_standard'),
    ('group:extra:reconstruction'), ('group:extra:reconstruction_claim');
$$;

-- Members must match the shared JS rule (getPoolsForGroupType +
-- normalizeExtraPoolSubtype + canonicalizeExtraPoolSubtype) exactly:
-- the canonical subtype decides membership, an unresolved extra_rule_profile
-- never drops a member, and only reconstruction + reconstruction_weapon_v1 is
-- remapped to reconstruction_claim. Unresolved metadata is labeled by the JS
-- legacy/observation layer; SQL still counts the stored rows of that member.
CREATE FUNCTION public.statistics_group_members() RETURNS TABLE(scope_key text,pool_id text)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $members$
  SELECT DISTINCT classified.scope_key,classified.pool_id FROM (
    SELECT metadata.pool_id,CASE
      WHEN metadata.type IN ('limited','limited_character') THEN 'group:limited'
      WHEN metadata.type IN ('weapon','limited_weapon') AND metadata.is_limited_weapon IS DISTINCT FROM false THEN 'group:weapon_limited'
      WHEN metadata.type IN ('weapon','limited_weapon') AND metadata.is_limited_weapon=false THEN 'group:weapon_standard'
      WHEN metadata.type='extra' AND metadata.canonical_subtype='reconstruction' THEN 'group:extra:reconstruction'
      WHEN metadata.type='extra' AND metadata.canonical_subtype='reconstruction_claim' THEN 'group:extra:reconstruction_claim'
    END AS scope_key
    FROM (
      SELECT p.pool_id,p.type,p.is_limited_weapon,
        CASE WHEN nullif(btrim(p.extra_subtype),'')='reconstruction'
          AND nullif(btrim(p.extra_rule_profile),'')='reconstruction_weapon_v1'
          THEN 'reconstruction_claim'
          ELSE nullif(btrim(p.extra_subtype),'') END AS canonical_subtype
      FROM public.get_app_visible_pools() p WHERE nullif(p.pool_id,'') IS NOT NULL
    ) metadata
  ) classified WHERE classified.scope_key IS NOT NULL;
$members$;

-- Catalog changes can add, hide, or reclassify members. Recount from history so
-- a newly visible pool also starts with its existing rows, not zero.
CREATE OR REPLACE FUNCTION public.invalidate_statistics_catalog() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
  INSERT INTO public.statistics_jobs(scope_key,total_pulls)
    SELECT 'pool:'||p.pool_id,count(h.id) FILTER (WHERE h.special_type IS DISTINCT FROM 'gift'
      AND h.rarity IN (4,5,6) AND nullif(btrim(h.game_uid::text),'') IS NOT NULL AND h.timestamp>to_timestamp(0))
    FROM (SELECT DISTINCT pool_id FROM public.get_app_visible_pools() WHERE nullif(pool_id,'') IS NOT NULL) p
    LEFT JOIN public.history h ON h.pool_id=p.pool_id GROUP BY p.pool_id
    ON CONFLICT(scope_key) DO UPDATE SET total_pulls=EXCLUDED.total_pulls;
  INSERT INTO public.statistics_jobs(scope_key,total_pulls)
    SELECT g.scope_key,count(h.id) FILTER (WHERE h.special_type IS DISTINCT FROM 'gift'
      AND h.rarity IN (4,5,6) AND nullif(btrim(h.game_uid::text),'') IS NOT NULL AND h.timestamp>to_timestamp(0))
    FROM public.statistics_group_keys() AS g(scope_key)
    LEFT JOIN public.statistics_group_members() m ON m.scope_key=g.scope_key
    LEFT JOIN public.history h ON h.pool_id=m.pool_id GROUP BY g.scope_key
    ON CONFLICT(scope_key) DO UPDATE SET total_pulls=EXCLUDED.total_pulls;
  UPDATE public.statistics_jobs SET revision=revision+1;
  RETURN NULL;
END $$;

CREATE OR REPLACE FUNCTION public.track_statistics_history() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE v_sql text; v_activity_source text;
BEGIN
  IF TG_OP='INSERT' THEN
    v_sql := 'SELECT pool_id,user_id,game_uid,server_scope,rarity,timestamp,special_type,1 AS delta FROM new_rows';
  ELSIF TG_OP='DELETE' THEN
    v_sql := 'SELECT pool_id,user_id,game_uid,server_scope,rarity,timestamp,special_type,-1 AS delta FROM old_rows';
  ELSE
    v_sql := 'SELECT pool_id,user_id,game_uid,server_scope,rarity,timestamp,special_type,1 AS delta FROM new_rows UNION ALL SELECT pool_id,user_id,game_uid,server_scope,rarity,timestamp,special_type,-1 AS delta FROM old_rows';
  END IF;
  -- Ownership-copy order and pity chains depend on the whole account history.
  -- Include old and new scopes, including deleted/moved rows, but never fan out
  -- to other accounts merely because they share a pool with the changed account.
  -- server_scope is generated by migration 147 as
  -- coalesce(nullif(btrim(server_id),''),'legacy') and is therefore never null
  -- for current rows. IS NOT DISTINCT FROM additionally keeps legacy/degraded
  -- null scopes in one bucket, matching the JS account key fallback ('unknown'),
  -- instead of silently missing those dependencies.
  EXECUTE 'WITH changes AS ('||v_sql||'),
    accounts AS (
      SELECT DISTINCT user_id,btrim(game_uid::text) AS game_uid,server_scope FROM changes
      WHERE nullif(btrim(game_uid::text),'''') IS NOT NULL
    ), affected_pools AS (
      SELECT pool_id FROM changes
      UNION
      SELECT h.pool_id FROM public.history h JOIN accounts a
        ON h.user_id IS NOT DISTINCT FROM a.user_id
        AND btrim(h.game_uid::text)=a.game_uid
        AND h.server_scope IS NOT DISTINCT FROM a.server_scope
    ), deltas AS (
      SELECT pool_id,sum(CASE WHEN special_type IS DISTINCT FROM ''gift'' AND rarity IN (4,5,6)
        AND nullif(btrim(game_uid::text),'''') IS NOT NULL AND timestamp>to_timestamp(0) THEN delta ELSE 0 END) AS delta
      FROM changes GROUP BY pool_id
    ), members AS (SELECT * FROM public.statistics_group_members()), scope_deltas AS (
      SELECT ''pool:''||a.pool_id AS scope_key,coalesce(d.delta,0) AS delta FROM affected_pools a
        LEFT JOIN deltas d ON d.pool_id=a.pool_id
        WHERE nullif(a.pool_id,'''') IS NOT NULL
      UNION ALL
      SELECT m.scope_key,sum(coalesce(d.delta,0)) FROM members m
        JOIN affected_pools a ON a.pool_id=m.pool_id LEFT JOIN deltas d ON d.pool_id=m.pool_id
        GROUP BY m.scope_key
    )
    INSERT INTO public.statistics_jobs(scope_key,total_pulls)
      SELECT scope_key,delta FROM scope_deltas ORDER BY scope_key
      ON CONFLICT(scope_key) DO UPDATE SET revision=statistics_jobs.revision+1,
        total_pulls=statistics_jobs.total_pulls+EXCLUDED.total_pulls';
  v_activity_source := CASE WHEN TG_OP='DELETE' THEN 'old_rows' ELSE 'new_rows' END;
  EXECUTE 'INSERT INTO public.statistics_activity(minute_at,contributor_id,changed_rows)
    SELECT date_trunc(''minute'',clock_timestamp()),user_id,count(*) FROM '||v_activity_source||'
    WHERE user_id IS NOT NULL GROUP BY user_id
    ON CONFLICT(minute_at,contributor_id) DO UPDATE SET changed_rows=statistics_activity.changed_rows+EXCLUDED.changed_rows';
  EXECUTE 'INSERT INTO public.statistics_jobs(scope_key) SELECT ''owner:''||user_id FROM ('||v_sql||') changes
    WHERE user_id IS NOT NULL GROUP BY user_id ORDER BY user_id
    ON CONFLICT(scope_key) DO UPDATE SET revision=statistics_jobs.revision+1';
  UPDATE public.statistics_jobs SET revision=revision+1 WHERE scope_key IN
    ('global_summary','character_ranking','character_catalog','public_analytics');
  RETURN NULL;
END $$;

CREATE OR REPLACE FUNCTION public.claim_statistics_job(p_lease uuid) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE v_minutes integer; v_rows10 bigint; v_rows60 bigint; v_users bigint; v_job public.statistics_jobs;
BEGIN
  SELECT coalesce(sum(changed_rows) FILTER (WHERE minute_at>=now()-interval '10 minutes'),0),
    coalesce(sum(changed_rows),0),count(DISTINCT contributor_id) FILTER (WHERE minute_at>=now()-interval '10 minutes')
    INTO v_rows10,v_rows60,v_users FROM public.statistics_activity WHERE minute_at>=now()-interval '60 minutes';
  v_minutes := CASE WHEN v_users>=5 OR v_rows10>=1000 THEN 5 WHEN v_rows60>0 THEN 30 ELSE 60 END;
  DELETE FROM public.statistics_activity WHERE minute_at<now()-interval '65 minutes';
  UPDATE public.statistics_jobs SET refresh_minutes=v_minutes,
    next_refresh_at=coalesce(computed_at,now())+make_interval(mins=>v_minutes)
    WHERE refresh_minutes IS DISTINCT FROM v_minutes AND computed_at IS NOT NULL;
  DELETE FROM public.statistics_jobs j WHERE
    (scope_key LIKE 'pool:%' AND NOT EXISTS(SELECT 1 FROM public.get_app_visible_pools() p WHERE 'pool:'||p.pool_id=j.scope_key))
    OR (scope_key LIKE 'group:%' AND NOT EXISTS(SELECT 1 FROM public.statistics_group_keys() g(scope_key) WHERE g.scope_key=j.scope_key))
    OR (scope_key LIKE 'owner:%' AND NOT EXISTS(SELECT 1 FROM public.profiles p WHERE 'owner:'||p.id=j.scope_key));
  DELETE FROM public.statistics_snapshots s WHERE NOT EXISTS(SELECT 1 FROM public.statistics_jobs j WHERE j.scope_key=s.scope_key);
  UPDATE public.statistics_jobs SET next_refresh_at=now()+make_interval(mins=>refresh_minutes)
    WHERE revision=published_revision AND scope_key<>'global_summary' AND next_refresh_at<=now();
  SELECT * INTO v_job FROM public.statistics_jobs j
    WHERE (revision<>published_revision OR scope_key='global_summary')
      AND (computed_at IS NULL OR next_refresh_at<=now())
      AND (lease_until IS NULL OR lease_until<now()) AND (retry_at IS NULL OR retry_at<=now())
    ORDER BY next_refresh_at,CASE WHEN scope_key LIKE 'owner:%' THEN 2
      WHEN scope_key LIKE 'pool:%' OR scope_key LIKE 'group:%' THEN 1 ELSE 0 END,scope_key
    FOR UPDATE SKIP LOCKED LIMIT 1;
  IF NOT FOUND THEN RETURN NULL; END IF;
  UPDATE public.statistics_jobs SET lease_id=p_lease,lease_until=now()+interval '5 minutes',refresh_minutes=v_minutes
    WHERE scope_key=v_job.scope_key;
  RETURN jsonb_build_object('scopeKey',v_job.scope_key,'revision',v_job.revision,'refreshMinutes',v_minutes);
END $$;

CREATE FUNCTION public.read_statistics_group_counts() RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$
  SELECT coalesce(jsonb_object_agg(g.scope_key,coalesce(j.total_pulls,0)),'{}'::jsonb)
    FROM public.statistics_group_keys() g(scope_key)
    LEFT JOIN public.statistics_jobs j ON j.scope_key=g.scope_key;
$$;

INSERT INTO public.statistics_jobs(scope_key,total_pulls)
  SELECT g.scope_key,count(h.id) FILTER (WHERE h.special_type IS DISTINCT FROM 'gift'
    AND h.rarity IN (4,5,6) AND nullif(btrim(h.game_uid::text),'') IS NOT NULL AND h.timestamp>to_timestamp(0))
  FROM public.statistics_group_keys() g(scope_key)
  LEFT JOIN public.statistics_group_members() m ON m.scope_key=g.scope_key
  LEFT JOIN public.history h ON h.pool_id=m.pool_id GROUP BY g.scope_key;

-- Snapshot payload composition changed for every scope kind: pool payloads add
-- the scoped legacy section, owner payloads add per-group sections, group
-- payloads carry the member signature, and the legacy scopes republish under the
-- new schema version. Existing snapshots were also built before account-wide
-- dependency invalidation, so every scope must recompute exactly once.
-- revision<>published_revision is this schema's dirty flag; clearing computed_at
-- keeps a scope immediately claimable so the adaptive cadence cannot defer the
-- forced refresh, and retry_at is cleared so backoff does not hide the upgrade.
UPDATE public.statistics_jobs
SET revision=revision+1,computed_at=NULL,next_refresh_at=now(),retry_at=NULL
WHERE true;

REVOKE ALL ON FUNCTION public.statistics_group_keys(),public.statistics_group_members(),
  public.read_statistics_group_counts() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.statistics_group_keys(),public.statistics_group_members(),
  public.read_statistics_group_counts() TO service_role;
-- Replaced functions retain their prior ACLs; restate service-only contracts.
REVOKE ALL ON FUNCTION public.track_statistics_history(),public.invalidate_statistics_catalog(),
  public.claim_statistics_job(uuid) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.claim_statistics_job(uuid) TO service_role;
COMMENT ON FUNCTION public.read_statistics_group_counts() IS
  'Service-only JSON map keyed by full group: scope; counts eligible stored rows across visible member pools, not distinct accounts or observations.';
NOTIFY pgrst, 'reload schema';
COMMIT;
